include:
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/java/abstracts/gradle.yaml'

.gradle-application:
  extends: '.gradle'
  cache:
    paths:
      - '.gradle'
      - '.gradle-home/caches'
      - '.gradle-home/notifications'
      - 'build'
      - 'buildSrc/.gradle'
      - 'buildSrc/build'
